#ifndef KPPBARCODEREADER_GLOBAL
#define KPPBARCODEREADER_GLOBAL



#include <QtCore/qglobal.h>
#include "QZXing.h"

#if defined(KPPBARCODEREADER_LIBRARY)
#  define KPPBARCODEREADER_EXPORT Q_DECL_EXPORT
#else
#  define KPPBARCODEREADER_EXPORT Q_DECL_IMPORT
#endif




#endif // KPPBARCODEREADER_GLOBAL

